import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Home/Sidebar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div className="flex min-h-screen bg-[#0f0f0f]">
					{/* Sidebar - Ensure Fixed Width */}
					<Sidebar  />

					{/* Main Content Wrapper */}
					<div className="flex-1 flex flex-col md:ml-16 ml-4">
						{/* Navbar (Fixed at the Top) */}
						<Navbar />

						{/* Main Page Content */}
						<main className="p-6 mt-16">{children}</main>
					</div>
				</div>
			</body>
		</html>
	);
}
